---
- hosts: SlaveNode
  become: true
  tasks:
  - name: Install Docker
    apt:
      update_cache: yes
      pkg: docker.io
      state: present
  - name: Start Docker services
    service:
      name: docker
      state: started
      enabled: true
  - name: deploy addressbook application
    command: sudo docker run -d -p 8888:8888 diablonemesis/casestudy:1.0
